### ISSUE TITLE
Set event user agent before running the enrichments

### ISSUE THREAD

**Issue by benjben** [snowplow/common-enrich#16]
In https://github.com/snowplow/common-enrich/commit/6d32dccd1b1b349d29eb51cf42f0365082774799 user agent of the event got set to `ua` query string parameter if set. But this is done after the enrichments are run and consequently the enrichments that use user agent (e.g. YAUAA), don't use the right value.

**Comment by chuwy** [comment]
If we just set it before - it will exact same behavior as it pre-https://github.com/snowplow/common-enrich/commit/6d32dccd1b1b349d29eb51cf42f0365082774799

**Comment by benjben** [comment]
`setUseragent` needs to be called before the `transform`

**Comment by benjben** [comment]
This bug is there since at least Beam Enrich 1.0.0. I didn't try with 0.4.0, as the integration tests back then were in Stream Enrich.

**Comment by AcidFlow** [comment]
I just noticed that bug in my production environment too.

Would you have an ETA of when this fix will be available?

**Comment by benjben** [comment]
Hi @AcidFlow , we plan to release the new version of Stream Enrich and Beam Enrich today

**Comment by benjben** [comment]
Hi @AcidFlow ,

Stream Enrich 1.1.3-rc1 and Beam Enrich 1.2.3-rc1 are out.
They will run on our QA pipelines this weekend and we'll release the final versions on Monday.

**Comment by AcidFlow** [comment]
Hi @benjben,

Thanks for the update and the quick bug fix, it's really appreciated :)
Good luck with QA and the release :)

**Comment by benjben** [comment]
Hi @AcidFlow ,

New assets have been released : https://discourse.snowplowanalytics.com/t/beam-enrich-1-2-3-and-stream-enrich-1-1-3-released/3927
